ALTER TABLE review_units ADD COLUMN start_line INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_units ADD COLUMN end_line INTEGER NOT NULL DEFAULT 0;
ALTER TABLE review_units ADD COLUMN diff_hunk TEXT NOT NULL DEFAULT '';
