CREATE TABLE verified_findings (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  candidate_id TEXT NOT NULL REFERENCES candidate_findings(id) ON DELETE CASCADE,
  trace_id TEXT NOT NULL REFERENCES review_traces(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  confidence TEXT NOT NULL CHECK (confidence IN ('confirmed', 'advisory')),
  verification_source TEXT NOT NULL,
  verification_reason TEXT NOT NULL,
  category TEXT NOT NULL,
  severity TEXT NOT NULL,
  file_path TEXT NOT NULL,
  line INTEGER NOT NULL,
  title TEXT NOT NULL,
  explanation TEXT NOT NULL,
  evidence_json TEXT NOT NULL,
  suggestion TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(run_id, fingerprint)
);
